// const MoodHistory = require('../models/moodHistory');

// // ✅ Hardcoded songs — No API needed, always works!
// const songDatabase = {
//   happy: {
//     tamil: [
//       { name: 'Vaathi Coming', artist: 'Anirudh Ravichander', artwork: 'https://i.imgur.com/placeholder.jpg', spotifyUrl: 'https://open.spotify.com/search/Vaathi%20Coming%20Anirudh' },
//       { name: 'Arabic Kuthu', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Arabic%20Kuthu%20Anirudh' },
//       { name: 'Whistle Podu', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Whistle%20Podu%20Anirudh' },
//       { name: 'Aaluma Doluma', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Aaluma%20Doluma' },
//       { name: 'Jolly O Gymkhana', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jolly%20O%20Gymkhana' },
//       { name: 'Neruppu Da', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Neruppu%20Da%20Anirudh' },
//     ],
//     hindi: [
//       { name: 'Badtameez Dil', artist: 'Pritam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Badtameez%20Dil' },
//       { name: 'London Thumakda', artist: 'Sachin Jigar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/London%20Thumakda' },
//       { name: 'Balam Pichkari', artist: 'Vishal Shekhar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Balam%20Pichkari' },
//       { name: 'Gallan Goodiyaan', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gallan%20Goodiyaan' },
//       { name: 'Nagada Sang Dhol', artist: 'Shreya Ghoshal', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nagada%20Sang%20Dhol' },
//       { name: 'Malhari', artist: 'Vishal Shekhar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Malhari' },
//     ],
//     english: [
//       { name: 'Happy', artist: 'Pharrell Williams', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Happy%20Pharrell%20Williams' },
//       { name: 'Uptown Funk', artist: 'Bruno Mars', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Uptown%20Funk%20Bruno%20Mars' },
//       { name: "Can't Stop the Feeling", artist: 'Justin Timberlake', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Cant%20Stop%20The%20Feeling' },
//       { name: 'Good as Hell', artist: 'Lizzo', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Good%20As%20Hell%20Lizzo' },
//       { name: 'Walking on Sunshine', artist: 'Katrina and The Waves', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Walking%20On%20Sunshine' },
//       { name: 'Shake It Off', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shake%20It%20Off%20Taylor%20Swift' },
//     ],
//     telugu: [
//       { name: 'Butta Bomma', artist: 'Armaan Malik', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Butta%20Bomma' },
//       { name: 'Naatu Naatu', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Naatu%20Naatu' },
//       { name: 'Samajavaragamana', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Samajavaragamana' },
//       { name: 'Seeti Maar', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Seeti%20Maar%20Telugu' },
//       { name: 'Dhinka Chika', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dhinka%20Chika' },
//     ],
//   },
//   sad: {
//     tamil: [
//       { name: 'Munbe Vaa', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Munbe%20Vaa%20AR%20Rahman'},
//       { name: 'Nenjame', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nenjame%20Harris%20Jayaraj' },
//       { name: 'Ennodu Nee Irundhaal', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ennodu%20Nee%20Irundhaal' },
//       { name: 'Idhazhin Oram', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Idhazhin%20Oram' },
//       { name: 'Vinnaithaandi Varuvaayaa', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vinnaithaandi%20Varuvaayaa' },
//       { name: 'Nee Paartha Vizhigal', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nee%20Paartha%20Vizhigal' },
//     ],
//     hindi: [
//       { name: 'Channa Mereya', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Channa%20Mereya%20Arijit' },
//       { name: 'Tum Hi Ho', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tum%20Hi%20Ho%20Arijit' },
//       { name: 'Agar Tum Saath Ho', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Agar%20Tum%20Saath%20Ho' },
//       { name: 'Kabira', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kabira%20Arijit' },
//       { name: 'Phir Bhi Tumko Chahunga', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Phir%20Bhi%20Tumko%20Chahunga' },
//       { name: 'Lag Ja Gale', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lag%20Ja%20Gale' },
//     ],
//     english: [
//       { name: 'Someone Like You', artist: 'Adele', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Someone%20Like%20You%20Adele' },
//       { name: 'Let Her Go', artist: 'Passenger', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Let%20Her%20Go%20Passenger' },
//       { name: 'Fix You', artist: 'Coldplay', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Fix%20You%20Coldplay' },
//       { name: 'Stay With Me', artist: 'Sam Smith', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Stay%20With%20Me%20Sam%20Smith' },
//       { name: 'The Night We Met', artist: 'Lord Huron', artwork: '', spotifyUrl: 'https://open.spotify.com/search/The%20Night%20We%20Met' },
//       { name: 'All I Want', artist: 'Kodaline', artwork: '', spotifyUrl: 'https://open.spotify.com/search/All%20I%20Want%20Kodaline' },
//     ],
//     telugu: [
//       { name: 'Ye Fontana', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ye%20Fontana%20Sid%20Sriram' },
//       { name: 'Srivalli', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Srivalli%20Sid%20Sriram' },
//       { name: 'Inkem Inkem', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Inkem%20Inkem%20Sid%20Sriram' },
//       { name: 'Jalaja', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jalaja%20Telugu' },
//       { name: 'Nee Kannu Neeru', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nee%20Kannu%20Neeru%20Telugu' },
//     ],
//   },
//   angry: {
//     tamil: [
//       { name: 'Beast Mode', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Beast%20Mode%20Anirudh' },
//       { name: 'Mersal Arasan', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mersal%20Arasan' },
//       { name: 'Verithanam', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Verithanam%20AR%20Rahman' },
//       { name: 'Enjoy Enjaami', artist: 'Dhee ft Arivu', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Enjoy%20Enjaami' },
//       { name: 'Kutti Story', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kutti%20Story%20Anirudh' },
//       { name: 'Danga Maari Oodhari', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Danga%20Maari%20Oodhari' },
//     ],
//     hindi: [
//       { name: 'Mere Gully Mein', artist: 'Divine', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mere%20Gully%20Mein%20Divine' },
//       { name: 'Wakhra Swag', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wakhra%20Swag%20Badshah' },
//       { name: 'Gali Gali', artist: 'KK', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gali%20Gali%20Hindi' },
//       { name: 'Zinda', artist: 'Siddharth Mahadevan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Zinda%20Bhaag%20Hindi' },
//       { name: 'Sher Aaya Sher', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sher%20Aaya%20Sher' },
//     ],
//     english: [
//       { name: 'In The End', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/In%20The%20End%20Linkin%20Park' },
//       { name: 'Numb', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Numb%20Linkin%20Park' },
//       { name: 'Wake Me Up Inside', artist: 'Evanescence', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wake%20Me%20Up%20Evanescence' },
//       { name: 'Break Stuff', artist: 'Limp Bizkit', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Break%20Stuff%20Limp%20Bizkit' },
//       { name: 'Given Up', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Given%20Up%20Linkin%20Park' },
//     ],
//     telugu: [
//       { name: 'Saaho BGM', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Saaho%20BGM%20DSP' },
//       { name: 'RRR Theme', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/RRR%20Theme%20Keeravani' },
//       { name: 'Pushpa Mass BGM', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pushpa%20BGM%20DSP' },
//       { name: 'Oo Antava', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oo%20Antava%20DSP' },
//       { name: 'Jago Jago', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jago%20Jago%20Telugu' },
//     ],
//   },
//   neutral: {
//     tamil: [
//       { name: 'En Iniya Pon Nilave', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/En%20Iniya%20Pon%20Nilave' },
//       { name: 'Chinna Chinna Aasai', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chinna%20Chinna%20Aasai' },
//       { name: 'Poo Malai Vaangi', artist: 'SPB', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Poo%20Malai%20Vaangi%20SPB' },
//       { name: 'Thenmerku Paruvakatru', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thenmerku%20Paruvakatru' },
//       { name: 'Roja Janani', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Roja%20Janani%20AR%20Rahman' },
//     ],
//     hindi: [
//       { name: 'Lag Ja Gale', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lag%20Ja%20Gale%20Lata' },
//       { name: 'Yeh Dosti', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Yeh%20Dosti%20Kishore' },
//       { name: 'Zindagi Ek Safar', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Zindagi%20Ek%20Safar' },
//       { name: 'Ajeeb Dastan Hai Yeh', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ajeeb%20Dastan%20Hai%20Yeh' },
//       { name: 'Ek Pyaar Ka Nagma Hai', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ek%20Pyaar%20Ka%20Nagma' },
//     ],
//     english: [
//       { name: 'Imagine', artist: 'John Lennon', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Imagine%20John%20Lennon' },
//       { name: 'Hotel California', artist: 'Eagles', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hotel%20California%20Eagles' },
//       { name: 'Bohemian Rhapsody', artist: 'Queen', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bohemian%20Rhapsody%20Queen' },
//       { name: 'Let It Be', artist: 'The Beatles', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Let%20It%20Be%20Beatles' },
//       { name: 'Wonderwall', artist: 'Oasis', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wonderwall%20Oasis' },
//     ],
//     telugu: [
//       { name: 'Annamayya Keerthana', artist: 'SP Balasubrahmanyam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Annamayya%20SPB' },
//       { name: 'Evaro Evaro', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Evaro%20Evaro%20Telugu' },
//       { name: 'Nee Cheli', artist: 'SP Balasubrahmanyam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nee%20Cheli%20SPB' },
//       { name: 'Manmadhudu Theme', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Manmadhudu%20Telugu' },
//       { name: 'Ye Tara', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ye%20Tara%20Telugu' },
//     ],
//   },
//   fearful: {
//     tamil: [
//       { name: 'Suprabhatham', artist: 'MS Subbulakshmi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Suprabhatham%20MS%20Subbulakshmi' },
//       { name: 'Thiruppugazh', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thiruppugazh%20Tamil' },
//       { name: 'Karpagame', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Karpagame%20Ilaiyaraaja' },
//       { name: 'Murugan Devotional', artist: 'SPB', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Murugan%20Songs%20SPB' },
//       { name: 'Om Namah Shivaya', artist: 'SPB', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Om%20Namah%20Shivaya%20Tamil' },
//     ],
//     hindi: [
//       { name: 'Hanuman Chalisa', artist: 'Hariharan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hanuman%20Chalisa%20Hariharan' },
//       { name: 'Om Jai Jagdish', artist: 'Anuradha Paudwal', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Om%20Jai%20Jagdish%20Hare' },
//       { name: 'Gayatri Mantra', artist: 'Anuradha Paudwal', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gayatri%20Mantra' },
//       { name: 'Mahamrityunjaya Mantra', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mahamrityunjaya%20Mantra' },
//       { name: 'Jai Ambe Gauri', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jai%20Ambe%20Gauri' },
//     ],
//     english: [
//       { name: 'Moonlight Sonata', artist: 'Beethoven', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Moonlight%20Sonata%20Beethoven' },
//       { name: 'Clair de Lune', artist: 'Debussy', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Clair%20De%20Lune%20Debussy' },
//       { name: 'Canon in D', artist: 'Pachelbel', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Canon%20In%20D%20Pachelbel' },
//       { name: 'Ave Maria', artist: 'Schubert', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ave%20Maria%20Schubert' },
//       { name: 'Fur Elise', artist: 'Beethoven', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Fur%20Elise%20Beethoven' },
//     ],
//     telugu: [
//       { name: 'Venkateswara Suprabhatham', artist: 'MS Subbulakshmi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Venkateswara%20Suprabhatham' },
//       { name: 'Annamayya Devotional', artist: 'SP Balasubrahmanyam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Annamayya%20Devotional%20SPB' },
//       { name: 'Govinda Namalu', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Govinda%20Namalu%20Telugu' },
//       { name: 'Durga Devi Stotram', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Durga%20Stotram%20Telugu' },
//       { name: 'Lalitha Sahasranamam', artist: 'MS Subbulakshmi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lalitha%20Sahasranamam' },
//     ],
//   },
//   disgusted: {
//     tamil: [
//       { name: 'Carnatic Flute', artist: 'N Ramani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Carnatic%20Flute%20N%20Ramani' },
//       { name: 'Veena Meditation', artist: 'E Gayathri', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Veena%20Classical%20Tamil' },
//       { name: 'Tamil Instrumental', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tamil%20Instrumental%20Ilaiyaraaja' },
//       { name: 'Nadhaswaram Classical', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nadhaswaram%20Classical' },
//       { name: 'Sitar Tamil Ragas', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sitar%20Tamil%20Ragas' },
//     ],
//     hindi: [
//       { name: 'Raag Yaman', artist: 'Pandit Ravi Shankar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Raag%20Yaman%20Ravi%20Shankar' },
//       { name: 'Flute Meditation', artist: 'Hariprasad Chaurasia', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hariprasad%20Chaurasia%20Flute' },
//       { name: 'Tabla Classical', artist: 'Zakir Hussain', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Zakir%20Hussain%20Tabla' },
//       { name: 'Sitar Bhairavi', artist: 'Vilayat Khan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vilayat%20Khan%20Sitar' },
//       { name: 'Morning Ragas', artist: 'Pandit Ravi Shankar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Morning%20Ragas%20Ravi%20Shankar' },
//     ],
//     english: [
//       { name: 'Lofi Hip Hop Beats', artist: 'ChilledCow', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lofi%20Hip%20Hop%20Beats' },
//       { name: 'Rain Sounds', artist: 'Nature Sounds', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rain%20Sounds%20Relaxing' },
//       { name: 'Ocean Waves', artist: 'Nature Sounds', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ocean%20Waves%20Relaxing' },
//       { name: 'Piano Meditation', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Piano%20Meditation%20Music' },
//       { name: 'Study Lofi', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Study%20Lofi%20Music' },
//     ],
//     telugu: [
//       { name: 'Telugu Flute Classical', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Telugu%20Flute%20Classical' },
//       { name: 'Carnatic Violin', artist: 'L Subramaniam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/L%20Subramaniam%20Violin' },
//       { name: 'Veena Classical Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Veena%20Classical%20Telugu' },
//       { name: 'Telugu Meditation', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Telugu%20Meditation%20Music' },
//       { name: 'Sitar Ragas Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sitar%20Ragas%20Telugu' },
//     ],
//   },
//   surprised: {
//     tamil: [
//       { name: 'Why This Kolaveri Di', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Why%20This%20Kolaveri%20Di' },
//       { name: 'Selfie Pulla', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Selfie%20Pulla%20Anirudh' },
//       { name: 'Maari Thara Local', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Maari%20Thara%20Local' },
//       { name: 'Iphone Kaadhali', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Iphone%20Kaadhali%20Anirudh' },
//       { name: 'Taxi Taxi', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Taxi%20Taxi%20Tamil' },
//     ],
//     hindi: [
//       { name: 'Lungi Dance', artist: 'Yo Yo Honey Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lungi%20Dance%20Honey%20Singh' },
//       { name: 'Party Toh Banti Hai', artist: 'Mika Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Party%20Toh%20Banti%20Hai' },
//       { name: 'Abhi Toh Party Shuru Hui Hai', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Abhi%20Toh%20Party%20Shuru%20Hui' },
//       { name: 'Saturday Saturday', artist: 'Indeep Bakshi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Saturday%20Saturday%20Indeep%20Bakshi' },
//       { name: 'Desi Beat', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Desi%20Beat%20Badshah' },
//     ],
//     english: [
//       { name: 'Shake It Off', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shake%20It%20Off%20Taylor%20Swift' },
//       { name: 'Roar', artist: 'Katy Perry', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Roar%20Katy%20Perry' },
//       { name: 'Dynamite', artist: 'BTS', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dynamite%20BTS' },
//       { name: 'Blinding Lights', artist: 'The Weeknd', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Blinding%20Lights%20Weeknd' },
//       { name: 'Levitating', artist: 'Dua Lipa', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Levitating%20Dua%20Lipa' },
//     ],
//     telugu: [
//       { name: 'Dhinka Chika', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dhinka%20Chika%20Telugu' },
//       { name: 'Rangamma Mangamma', artist: 'SS Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rangamma%20Mangamma%20Telugu' },
//       { name: 'Pattas Theme', artist: 'Vivek Mervin', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pattas%20Telugu' },
//       { name: 'Uppena Fun Song', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Uppena%20Songs%20Telugu' },
//       { name: 'Rowdy Baby Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rowdy%20Baby%20Telugu' },
//     ],
//   },
// };

// const getRecommendations = async (req, res) => {
//   try {
//     const { emotion, language, userEmail } = req.query;

//     if (!emotion || !language) {
//       return res.status(400).json({ message: 'emotion and language required' });
//     }

//     const emotionLower = emotion.toLowerCase();
//     const languageLower = language.toLowerCase();

//     // ✅ MongoDB-ல Mood History save
//     if (userEmail) {
//       try {
//         await MoodHistory.create({
//           userEmail,
//           emotion: emotionLower,
//           language: languageLower,
//         });
//         console.log(`✅ Mood saved: ${userEmail} → ${emotionLower} → ${languageLower}`);
//       } catch (dbErr) {
//         console.log('⚠️ Mood save skipped:', dbErr.message);
//       }
//     }

//     // ✅ Database-லிருந்து songs எடு — No API, instant!
//     const songs = songDatabase[emotionLower]?.[languageLower] || [];

//     if (songs.length === 0) {
//       console.log(`⚠️ No songs for ${emotionLower}+${languageLower}`);
//       return res.json({ songs: [], emotion: emotionLower, language: languageLower });
//     }

//     console.log(`✅ Returning ${songs.length} songs for ${emotionLower}+${languageLower}`);
//     res.json({ songs, emotion: emotionLower, language: languageLower });

//   } catch (error) {
//     console.error('❌ Error:', error.message);
//     res.status(500).json({ message: 'Error', error: error.message });
//   }
// };

// module.exports = { getRecommendations };


const MoodHistory = require('../models/moodHistory');

const songDatabase = {
  happy: {
    tamil: [
      { name: 'Vaathi Coming', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vaathi%20Coming%20Anirudh' },
      { name: 'Arabic Kuthu', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Arabic%20Kuthu%20Anirudh' },
      { name: 'Whistle Podu', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Whistle%20Podu%20Anirudh' },
      { name: 'Aaluma Doluma', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Aaluma%20Doluma' },
      { name: 'Jolly O Gymkhana', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jolly%20O%20Gymkhana' },
      { name: 'Neruppu Da', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Neruppu%20Da%20Anirudh' },
      { name: 'Selfie Pulla', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Selfie%20Pulla%20Anirudh' },
      { name: 'Maari Thara Local', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Maari%20Thara%20Local' },
      { name: 'Danga Maari Oodhari', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Danga%20Maari%20Oodhari' },
      { name: 'Enjoy Enjaami', artist: 'Dhee ft Arivu', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Enjoy%20Enjaami' },
      { name: 'Kannaana Kanney', artist: 'D Imman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kannaana%20Kanney%20D%20Imman' },
      { name: 'Rowdy Baby', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rowdy%20Baby%20Tamil' },
      { name: 'Kutti Story', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kutti%20Story%20Anirudh' },
      { name: 'Oorvasi Oorvasi', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oorvasi%20Oorvasi%20AR%20Rahman' },
      { name: 'Urvasi Urvasi', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Urvasi%20AR%20Rahman' },
      { name: 'Why This Kolaveri Di', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Why%20This%20Kolaveri%20Di' },
      { name: 'Iphone Kaadhali', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Iphone%20Kaadhali%20Anirudh' },
      { name: 'Taxi Taxi', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Taxi%20Taxi%20Tamil' },
      { name: 'Chellamma', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chellamma%20Anirudh' },
      { name: 'Kaavaalaa', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kaavaalaa%20Anirudh' },
      { name: 'Jigidi Killaadi', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jigidi%20Killaadi%20Anirudh' },
      { name: 'Naattu Koothu', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Naattu%20Koothu%20Tamil' },
      { name: 'Kannamoochi Yenada', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kannamoochi%20Yenada%20AR%20Rahman' },
      { name: 'Appadi Podu', artist: 'Vijay Antony', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Appadi%20Podu%20Tamil' },
      { name: 'Surviva', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Surviva%20Anirudh' },
    ],
    hindi: [
      { name: 'Badtameez Dil', artist: 'Pritam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Badtameez%20Dil' },
      { name: 'London Thumakda', artist: 'Sachin Jigar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/London%20Thumakda' },
      { name: 'Balam Pichkari', artist: 'Vishal Shekhar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Balam%20Pichkari' },
      { name: 'Gallan Goodiyaan', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gallan%20Goodiyaan' },
      { name: 'Nagada Sang Dhol', artist: 'Shreya Ghoshal', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nagada%20Sang%20Dhol' },
      { name: 'Malhari', artist: 'Vishal Shekhar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Malhari' },
      { name: 'Kar Gayi Chull', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kar%20Gayi%20Chull%20Badshah' },
      { name: 'Abhi Toh Party Shuru Hui Hai', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Abhi%20Toh%20Party%20Shuru%20Hui' },
      { name: 'Saturday Saturday', artist: 'Indeep Bakshi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Saturday%20Saturday%20Indeep%20Bakshi' },
      { name: 'Desi Beat', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Desi%20Beat%20Badshah' },
      { name: 'Lungi Dance', artist: 'Yo Yo Honey Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lungi%20Dance%20Honey%20Singh' },
      { name: 'Party Toh Banti Hai', artist: 'Mika Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Party%20Toh%20Banti%20Hai' },
      { name: 'Seeti Maar', artist: 'Yo Yo Honey Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Seeti%20Maar%20Hindi' },
      { name: 'Wakhra Swag', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wakhra%20Swag%20Badshah' },
      { name: 'DJ Waale Babu', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/DJ%20Waale%20Babu%20Badshah' },
      { name: 'Gandi Baat', artist: 'Meet Bros', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gandi%20Baat%20Hindi' },
      { name: 'Proper Patola', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Proper%20Patola%20Badshah' },
      { name: 'Nach Meri Rani', artist: 'Guru Randhawa', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nach%20Meri%20Rani' },
      { name: 'Paani Paani', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Paani%20Paani%20Badshah' },
      { name: 'Garmi', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Garmi%20Badshah' },
      { name: 'Dilbar', artist: 'Neha Kakkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dilbar%20Neha%20Kakkar' },
      { name: 'Swag Se Swagat', artist: 'Vishal Shekhar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Swag%20Se%20Swagat' },
      { name: 'Bom Diggy', artist: 'Zack Knight', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bom%20Diggy%20Zack%20Knight' },
      { name: 'Akh Lad Jaave', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Akh%20Lad%20Jaave%20Badshah' },
      { name: 'Saki Saki', artist: 'Neha Kakkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Saki%20Saki%20Neha%20Kakkar' },
    ],
    english: [
      { name: 'Happy', artist: 'Pharrell Williams', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Happy%20Pharrell%20Williams' },
      { name: 'Uptown Funk', artist: 'Bruno Mars', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Uptown%20Funk%20Bruno%20Mars' },
      { name: "Can't Stop the Feeling", artist: 'Justin Timberlake', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Cant%20Stop%20The%20Feeling' },
      { name: 'Good as Hell', artist: 'Lizzo', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Good%20As%20Hell%20Lizzo' },
      { name: 'Walking on Sunshine', artist: 'Katrina and The Waves', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Walking%20On%20Sunshine' },
      { name: 'Shake It Off', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shake%20It%20Off%20Taylor%20Swift' },
      { name: 'Dynamite', artist: 'BTS', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dynamite%20BTS' },
      { name: 'Blinding Lights', artist: 'The Weeknd', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Blinding%20Lights%20Weeknd' },
      { name: 'Levitating', artist: 'Dua Lipa', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Levitating%20Dua%20Lipa' },
      { name: 'Roar', artist: 'Katy Perry', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Roar%20Katy%20Perry' },
      { name: 'Firework', artist: 'Katy Perry', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Firework%20Katy%20Perry' },
      { name: 'Counting Stars', artist: 'OneRepublic', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Counting%20Stars%20OneRepublic' },
      { name: 'Best Day of My Life', artist: 'American Authors', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Best%20Day%20Of%20My%20Life' },
      { name: "Don't Stop Me Now", artist: 'Queen', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dont%20Stop%20Me%20Now%20Queen' },
      { name: 'Dancing Queen', artist: 'ABBA', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dancing%20Queen%20ABBA' },
      { name: 'Shut Up and Dance', artist: 'Walk The Moon', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shut%20Up%20And%20Dance' },
      { name: 'I Gotta Feeling', artist: 'Black Eyed Peas', artwork: '', spotifyUrl: 'https://open.spotify.com/search/I%20Gotta%20Feeling%20Black%20Eyed%20Peas' },
      { name: 'Stronger', artist: 'Kanye West', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Stronger%20Kanye%20West' },
      { name: 'Party Rock Anthem', artist: 'LMFAO', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Party%20Rock%20Anthem%20LMFAO' },
      { name: 'Timber', artist: 'Pitbull', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Timber%20Pitbull' },
      { name: 'Cheap Thrills', artist: 'Sia', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Cheap%20Thrills%20Sia' },
      { name: 'Shape of You', artist: 'Ed Sheeran', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shape%20Of%20You%20Ed%20Sheeran' },
      { name: 'Something Just Like This', artist: 'Coldplay', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Something%20Just%20Like%20This%20Coldplay' },
      { name: 'Happier', artist: 'Marshmello', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Happier%20Marshmello' },
      { name: 'Sugar', artist: 'Maroon 5', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sugar%20Maroon%205' },
    ],
    telugu: [
      { name: 'Butta Bomma', artist: 'Armaan Malik', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Butta%20Bomma' },
      { name: 'Naatu Naatu', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Naatu%20Naatu' },
      { name: 'Samajavaragamana', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Samajavaragamana' },
      { name: 'Seeti Maar', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Seeti%20Maar%20Telugu' },
      { name: 'Dhinka Chika', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dhinka%20Chika' },
      { name: 'Rangamma Mangamma', artist: 'SS Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rangamma%20Mangamma%20Telugu' },
      { name: 'Rowdy Baby Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rowdy%20Baby%20Telugu' },
      { name: 'Oo Antava', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oo%20Antava%20DSP' },
      { name: 'Uppena Fun Song', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Uppena%20Songs%20Telugu' },
      { name: 'Pattas Theme', artist: 'Vivek Mervin', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pattas%20Telugu' },
      { name: 'Winner Winner', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Winner%20Winner%20Telugu' },
      { name: 'Gully Rowdy', artist: 'Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gully%20Rowdy%20Telugu' },
      { name: 'Jago Jago', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jago%20Jago%20Telugu' },
      { name: 'Buttabomma Remake', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Buttabomma%20Sid%20Sriram' },
      { name: 'Dhammu', artist: 'SS Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dhammu%20Telugu' },
      { name: 'Shyam Singha Roy', artist: 'Mickey J Meyer', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shyam%20Singha%20Roy%20Telugu' },
      { name: 'Kurchi Madathapetti', artist: 'Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kurchi%20Madathapetti%20Telugu' },
      { name: 'Kushi Title Song', artist: 'Hesham Abdul Wahab', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kushi%20Title%20Song%20Telugu' },
      { name: 'Gaami Song', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gaami%20Telugu' },
      { name: 'Waltair Veerayya', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Waltair%20Veerayya%20DSP' },
    ],
  },
  sad: {
    tamil: [
      { name: 'Munbe Vaa', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Munbe%20Vaa%20AR%20Rahman' },
      { name: 'Nenjame', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nenjame%20Harris%20Jayaraj' },
      { name: 'Ennodu Nee Irundhaal', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ennodu%20Nee%20Irundhaal' },
      { name: 'Idhazhin Oram', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Idhazhin%20Oram' },
      { name: 'Vinnaithaandi Varuvaayaa', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vinnaithaandi%20Varuvaayaa' },
      { name: 'Nee Paartha Vizhigal', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nee%20Paartha%20Vizhigal' },
      { name: 'Kadhal Sadugudu', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kadhal%20Sadugudu%20AR%20Rahman' },
      { name: 'Uyire Uyire', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Uyire%20Uyire%20AR%20Rahman' },
      { name: 'Vennilave Vennilave', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vennilave%20Vennilave%20AR%20Rahman' },
      { name: 'Mazhai Kuruvi', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mazhai%20Kuruvi%20AR%20Rahman' },
      { name: 'Nila Kaigirathu', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nila%20Kaigirathu%20Ilaiyaraaja' },
      { name: 'Kannamoochi Yenada Sad', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kannamoochi%20AR%20Rahman%20sad' },
      { name: 'Antha Arabi Kadallile', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Antha%20Arabi%20Kadallile' },
      { name: 'Unnai Kaanadhu Naan', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Unnai%20Kaanadhu%20Naan%20Harris' },
      { name: 'Yennai Maatrum Kadhale', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Yennai%20Maatrum%20Kadhale' },
      { name: 'Kadhal Rojave', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kadhal%20Rojave%20AR%20Rahman' },
      { name: 'Nenjukkul Peidhidum', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nenjukkul%20Peidhidum%20Harris' },
      { name: 'Roja Kanavugal', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Roja%20Kanavugal%20AR%20Rahman' },
      { name: 'Kanave Kanave', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kanave%20Kanave%20AR%20Rahman' },
      { name: 'Oh Manapenne', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oh%20Manapenne%20Yuvan' },
      { name: 'Solla Solla', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Solla%20Solla%20Harris%20Jayaraj' },
      { name: 'Thuli Thuli', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thuli%20Thuli%20AR%20Rahman' },
      { name: 'Naan Un Azhaginile', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Naan%20Un%20Azhaginile%20Harris' },
      { name: 'Oru Maalai', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oru%20Maalai%20Harris%20Jayaraj' },
      { name: 'Poove Poochudava', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Poove%20Poochudava%20Ilaiyaraaja' },
    ],
    hindi: [
      { name: 'Channa Mereya', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Channa%20Mereya%20Arijit' },
      { name: 'Tum Hi Ho', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tum%20Hi%20Ho%20Arijit' },
      { name: 'Agar Tum Saath Ho', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Agar%20Tum%20Saath%20Ho' },
      { name: 'Kabira', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kabira%20Arijit' },
      { name: 'Phir Bhi Tumko Chahunga', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Phir%20Bhi%20Tumko%20Chahunga' },
      { name: 'Lag Ja Gale', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lag%20Ja%20Gale' },
      { name: 'Ae Dil Hai Mushkil', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ae%20Dil%20Hai%20Mushkil%20Arijit' },
      { name: 'Soch Na Sake', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Soch%20Na%20Sake%20Arijit' },
      { name: 'Humdard', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Humdard%20Arijit%20Singh' },
      { name: 'Khairiyat', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Khairiyat%20Arijit%20Singh' },
      { name: 'Tera Ban Jaunga', artist: 'Akhil Sachdeva', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tera%20Ban%20Jaunga' },
      { name: 'Tujhe Kitna Chahne Lage', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tujhe%20Kitna%20Chahne%20Lage%20Arijit' },
      { name: 'Bekhayali', artist: 'Sachet Tandon', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bekhayali%20Kabir%20Singh' },
      { name: 'Kal Ho Naa Ho', artist: 'Sonu Nigam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kal%20Ho%20Naa%20Ho%20Sonu%20Nigam' },
      { name: 'Dil Dhadakne Do', artist: 'Shankar Ehsaan Loy', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dil%20Dhadakne%20Do' },
      { name: 'Raabta', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Raabta%20Arijit%20Singh' },
      { name: 'Shayad', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shayad%20Arijit%20Love%20Aaj%20Kal' },
      { name: 'Mere Naam Tu', artist: 'Abhay Jodhpurkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mere%20Naam%20Tu%20Zero' },
      { name: 'Hawayein', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hawayein%20Arijit%20Singh' },
      { name: 'Pehla Pyaar', artist: 'Armaan Malik', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pehla%20Pyaar%20Armaan%20Malik' },
      { name: 'Dil Ko Karaar Aaya', artist: 'Neha Kakkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dil%20Ko%20Karaar%20Aaya' },
      { name: 'Main Rang Sharbaton Ka', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Main%20Rang%20Sharbaton%20Ka' },
      { name: 'Iktara', artist: 'Amit Trivedi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Iktara%20Wake%20Up%20Sid' },
      { name: 'Tu Jaane Na', artist: 'Atif Aslam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tu%20Jaane%20Na%20Atif%20Aslam' },
      { name: 'Sajdaa', artist: 'Rahat Fateh Ali Khan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sajdaa%20Rahat%20Fateh%20Ali%20Khan' },
    ],
    english: [
      { name: 'Someone Like You', artist: 'Adele', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Someone%20Like%20You%20Adele' },
      { name: 'Let Her Go', artist: 'Passenger', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Let%20Her%20Go%20Passenger' },
      { name: 'Fix You', artist: 'Coldplay', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Fix%20You%20Coldplay' },
      { name: 'Stay With Me', artist: 'Sam Smith', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Stay%20With%20Me%20Sam%20Smith' },
      { name: 'The Night We Met', artist: 'Lord Huron', artwork: '', spotifyUrl: 'https://open.spotify.com/search/The%20Night%20We%20Met' },
      { name: 'All I Want', artist: 'Kodaline', artwork: '', spotifyUrl: 'https://open.spotify.com/search/All%20I%20Want%20Kodaline' },
      { name: 'Skinny Love', artist: 'Bon Iver', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Skinny%20Love%20Bon%20Iver' },
      { name: 'The Scientist', artist: 'Coldplay', artwork: '', spotifyUrl: 'https://open.spotify.com/search/The%20Scientist%20Coldplay' },
      { name: 'When The Party Is Over', artist: 'Billie Eilish', artwork: '', spotifyUrl: 'https://open.spotify.com/search/When%20The%20Party%20Is%20Over%20Billie%20Eilish' },
      { name: 'Liability', artist: 'Lorde', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Liability%20Lorde' },
      { name: 'Chasing Cars', artist: 'Snow Patrol', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chasing%20Cars%20Snow%20Patrol' },
      { name: 'Wildest Dreams', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wildest%20Dreams%20Taylor%20Swift' },
      { name: 'Photograph', artist: 'Ed Sheeran', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Photograph%20Ed%20Sheeran' },
      { name: 'Tears Dry On Their Own', artist: 'Amy Winehouse', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tears%20Dry%20On%20Their%20Own%20Amy%20Winehouse' },
      { name: 'Hello', artist: 'Adele', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hello%20Adele' },
      { name: 'Erase Me', artist: 'Billie Eilish', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Erase%20Me%20Billie%20Eilish' },
      { name: 'Yellow', artist: 'Coldplay', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Yellow%20Coldplay' },
      { name: 'Drivers License', artist: 'Olivia Rodrigo', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Drivers%20License%20Olivia%20Rodrigo' },
      { name: 'Happier', artist: 'Olivia Rodrigo', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Happier%20Olivia%20Rodrigo' },
      { name: 'Dancing With Your Ghost', artist: 'Sasha Sloan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dancing%20With%20Your%20Ghost%20Sasha%20Sloan' },
      { name: 'Through The Dark', artist: 'One Direction', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Through%20The%20Dark%20One%20Direction' },
      { name: 'Superstar', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Superstar%20Taylor%20Swift' },
      { name: 'Without You', artist: 'Mariah Carey', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Without%20You%20Mariah%20Carey' },
      { name: 'My Immortal', artist: 'Evanescence', artwork: '', spotifyUrl: 'https://open.spotify.com/search/My%20Immortal%20Evanescence' },
      { name: 'Last Kiss', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Last%20Kiss%20Taylor%20Swift' },
    ],
    telugu: [
      { name: 'Ye Fontana', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ye%20Fontana%20Sid%20Sriram' },
      { name: 'Srivalli', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Srivalli%20Sid%20Sriram' },
      { name: 'Inkem Inkem', artist: 'Sid Sriram', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Inkem%20Inkem%20Sid%20Sriram' },
      { name: 'Jalaja', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jalaja%20Telugu' },
      { name: 'Nee Kannu Neeru', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nee%20Kannu%20Neeru%20Telugu' },
      { name: 'Kannaana Kanney Telugu', artist: 'D Imman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kannaana%20Kanney%20Telugu' },
      { name: 'Nuvvu Nuvvu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nuvvu%20Nuvvu%20Telugu%20sad' },
      { name: 'Ye Preme', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ye%20Preme%20Telugu%20sad' },
      { name: 'Neeli Neeli Aakasam', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Neeli%20Neeli%20Aakasam%20Telugu' },
      { name: 'Evare Nuvvu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Evare%20Nuvvu%20Telugu' },
      { name: 'Manasuna Manasai', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Manasuna%20Manasai%20Telugu' },
      { name: 'Ye Tara', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ye%20Tara%20Telugu' },
      { name: 'Oohalu Gusagusalade', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oohalu%20Gusagusalade%20Telugu' },
      { name: 'Chinuku Taka', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chinuku%20Taka%20Telugu' },
      { name: 'Nalo Nuvvu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nalo%20Nuvvu%20Telugu' },
      { name: 'Peniviti', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Peniviti%20Telugu%20sad' },
      { name: 'Nee Jathaga Nenundaali', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nee%20Jathaga%20Nenundaali%20Telugu' },
      { name: 'Ye Prema Ye Prema', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ye%20Prema%20Ye%20Prema%20Telugu' },
      { name: 'Kalisundam Raa', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kalisundam%20Raa%20Telugu' },
      { name: 'Pilla Raa', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pilla%20Raa%20Telugu%20sad' },
    ],
  },
  angry: {
    tamil: [
      { name: 'Beast Mode', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Beast%20Mode%20Anirudh' },
      { name: 'Mersal Arasan', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mersal%20Arasan' },
      { name: 'Verithanam', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Verithanam%20AR%20Rahman' },
      { name: 'Enjoy Enjaami', artist: 'Dhee ft Arivu', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Enjoy%20Enjaami' },
      { name: 'Kutti Story', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kutti%20Story%20Anirudh' },
      { name: 'Danga Maari Oodhari', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Danga%20Maari%20Oodhari' },
      { name: 'Vaadi Vaadi', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vaadi%20Vaadi%20Tamil' },
      { name: 'Survivor Tamil', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Surviva%20Anirudh' },
      { name: 'Kaththi BGM', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kaththi%20BGM%20Anirudh' },
      { name: 'Bigil Theme', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bigil%20Theme%20AR%20Rahman' },
      { name: 'Master BGM', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Master%20BGM%20Anirudh' },
      { name: 'Thalapathy BGM', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thalapathy%20BGM%20AR%20Rahman' },
      { name: 'Sarkar Theme', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sarkar%20Theme%20AR%20Rahman' },
      { name: 'Varma Theme', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Varma%20Theme%20Tamil' },
      { name: 'Villain Theme Tamil', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Villain%20Theme%20Tamil%20Anirudh' },
      { name: 'Rajini BGM', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rajini%20BGM%20AR%20Rahman' },
      { name: 'Mankatha Theme', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mankatha%20Theme%20Yuvan' },
      { name: 'Soorarai Pottru BGM', artist: 'GV Prakash', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Soorarai%20Pottru%20BGM' },
      { name: 'Iruvar BGM', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Iruvar%20BGM%20AR%20Rahman' },
      { name: 'Kadaikutty Singam Theme', artist: 'D Imman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kadaikutty%20Singam%20Theme' },
    ],
    hindi: [
      { name: 'Mere Gully Mein', artist: 'Divine', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mere%20Gully%20Mein%20Divine' },
      { name: 'Wakhra Swag', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wakhra%20Swag%20Badshah' },
      { name: 'Gali Gali', artist: 'KK', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gali%20Gali%20Hindi' },
      { name: 'Zinda', artist: 'Siddharth Mahadevan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Zinda%20Bhaag%20Hindi' },
      { name: 'Sher Aaya Sher', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sher%20Aaya%20Sher' },
      { name: 'Jai Ho', artist: 'Salman Khan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jai%20Ho%20Salman%20Khan' },
      { name: 'Sultan Theme', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sultan%20Theme%20Bollywood' },
      { name: 'Dangal Title Track', artist: 'Pritam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dangal%20Title%20Track%20Pritam' },
      { name: 'Toofan', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Toofan%20Hindi%20angry' },
      { name: 'War Theme', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/War%20Theme%20Hindi%20film' },
      { name: 'Bloody Hell', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bloody%20Hell%20Hindi' },
      { name: 'Raftaar Mass BGM', artist: 'Raftaar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Raftaar%20mass%20bgm' },
      { name: 'Khatarnak', artist: 'Divine', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Khatarnak%20Divine' },
      { name: 'Farak', artist: 'Raftaar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Farak%20Raftaar' },
      { name: 'Sheher', artist: 'Raftaar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sheher%20Raftaar' },
      { name: 'Dilli Wali Girlfriend Angry', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dilli%20Wali%20Girlfriend%20angry' },
      { name: 'Jumme Ki Raat', artist: 'Salman Khan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jumme%20Ki%20Raat%20Salman' },
      { name: 'Dhoom Machale', artist: 'Sunidhi Chauhan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dhoom%20Machale%20Sunidhi' },
      { name: 'Bhaag DK Bose', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bhaag%20DK%20Bose%20Hindi' },
      { name: 'Chak De India', artist: 'Salim Merchant', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chak%20De%20India%20Salim%20Merchant' },
    ],
    english: [
      { name: 'In The End', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/In%20The%20End%20Linkin%20Park' },
      { name: 'Numb', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Numb%20Linkin%20Park' },
      { name: 'Wake Me Up Inside', artist: 'Evanescence', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wake%20Me%20Up%20Evanescence' },
      { name: 'Break Stuff', artist: 'Limp Bizkit', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Break%20Stuff%20Limp%20Bizkit' },
      { name: 'Given Up', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Given%20Up%20Linkin%20Park' },
      { name: 'Crawling', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Crawling%20Linkin%20Park' },
      { name: 'Killing In The Name', artist: 'Rage Against The Machine', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Killing%20In%20The%20Name%20RATM' },
      { name: 'Enter Sandman', artist: 'Metallica', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Enter%20Sandman%20Metallica' },
      { name: 'Master of Puppets', artist: 'Metallica', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Master%20Of%20Puppets%20Metallica' },
      { name: 'Back In Black', artist: 'ACDC', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Back%20In%20Black%20ACDC' },
      { name: 'Thunderstruck', artist: 'ACDC', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thunderstruck%20ACDC' },
      { name: 'Smells Like Teen Spirit', artist: 'Nirvana', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Smells%20Like%20Teen%20Spirit%20Nirvana' },
      { name: 'Lose Yourself', artist: 'Eminem', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lose%20Yourself%20Eminem' },
      { name: 'Till I Collapse', artist: 'Eminem', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Till%20I%20Collapse%20Eminem' },
      { name: 'Rap God', artist: 'Eminem', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rap%20God%20Eminem' },
      { name: 'Bulls On Parade', artist: 'Rage Against The Machine', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bulls%20On%20Parade%20RATM' },
      { name: 'Down With The Sickness', artist: 'Disturbed', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Down%20With%20The%20Sickness%20Disturbed' },
      { name: 'Faint', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Faint%20Linkin%20Park' },
      { name: 'Papercut', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Papercut%20Linkin%20Park' },
      { name: 'One Step Closer', artist: 'Linkin Park', artwork: '', spotifyUrl: 'https://open.spotify.com/search/One%20Step%20Closer%20Linkin%20Park' },
    ],
    telugu: [
      { name: 'Saaho BGM', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Saaho%20BGM%20DSP' },
      { name: 'RRR Theme', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/RRR%20Theme%20Keeravani' },
      { name: 'Pushpa Mass BGM', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pushpa%20BGM%20DSP' },
      { name: 'Oo Antava', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oo%20Antava%20DSP' },
      { name: 'Jago Jago', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jago%20Jago%20Telugu' },
      { name: 'Baahubali Theme', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Baahubali%20Theme%20Keeravani' },
      { name: 'Magadheera BGM', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Magadheera%20BGM%20Keeravani' },
      { name: 'Simha BGM', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Simha%20BGM%20DSP' },
      { name: 'Pokiri Theme', artist: 'Mani Sharma', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pokiri%20Theme%20Mani%20Sharma' },
      { name: 'Gabbar Singh Theme', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gabbar%20Singh%20Theme%20DSP' },
      { name: 'Sarrainodu Theme', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sarrainodu%20Theme%20DSP' },
      { name: 'Agnyaathavaasi BGM', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Agnyaathavaasi%20BGM%20Anirudh' },
      { name: 'Spyder BGM', artist: 'Harris Jayaraj', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Spyder%20BGM%20Harris%20Jayaraj' },
      { name: 'Julayi Mass', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Julayi%20Mass%20DSP' },
      { name: 'Temper BGM', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Temper%20BGM%20DSP' },
      { name: 'Race Gurram Theme', artist: 'S Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Race%20Gurram%20Theme%20Thaman' },
      { name: 'Attarintiki Daredi', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Attarintiki%20Daredi%20DSP' },
      { name: 'Krishnashtami Theme', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Krishnashtami%20Telugu%20mass' },
      { name: 'Akhil Theme', artist: 'Anup Rubens', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Akhil%20Theme%20Anup%20Rubens' },
      { name: 'Winner BGM', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Winner%20BGM%20DSP%20Telugu' },
    ],
  },
  neutral: {
    tamil: [
      { name: 'En Iniya Pon Nilave', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/En%20Iniya%20Pon%20Nilave' },
      { name: 'Chinna Chinna Aasai', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chinna%20Chinna%20Aasai' },
      { name: 'Poo Malai Vaangi', artist: 'SPB', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Poo%20Malai%20Vaangi%20SPB' },
      { name: 'Thenmerku Paruvakatru', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thenmerku%20Paruvakatru' },
      { name: 'Roja Janani', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Roja%20Janani%20AR%20Rahman' },
      { name: 'Kannamoochi Yenada', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kannamoochi%20Yenada%20AR%20Rahman' },
      { name: 'Aasai Aasai', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Aasai%20Aasai%20AR%20Rahman' },
      { name: 'Ennavale Adi Ennavale', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ennavale%20Adi%20AR%20Rahman' },
      { name: 'Idhu Varai', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Idhu%20Varai%20Ilaiyaraaja' },
      { name: 'Putham Pudhu Kaalai', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Putham%20Pudhu%20Kaalai%20AR%20Rahman' },
      { name: 'Panivizhum Malarvanam', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Panivizhum%20Malarvanam%20Ilaiyaraaja' },
      { name: 'En Kadhal Solla', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/En%20Kadhal%20Solla%20AR%20Rahman' },
      { name: 'Nee Partha Vizhigal', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nee%20Partha%20Vizhigal%20AR%20Rahman' },
      { name: 'Thenmadurai Vaigai Nadhi', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thenmadurai%20Vaigai%20Nadhi' },
      { name: 'Mannvanadi Nee', artist: 'SPB', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mannvanadi%20Nee%20SPB' },
      { name: 'Aval Appadithan', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Aval%20Appadithan%20Ilaiyaraaja' },
      { name: 'Ilamai Enum Poongatru', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ilamai%20Enum%20Poongatru%20Ilaiyaraaja' },
      { name: 'Mudhal Murai', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mudhal%20Murai%20AR%20Rahman' },
      { name: 'Ninaithale Inikkum', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ninaithale%20Inikkum%20Ilaiyaraaja' },
      { name: 'Kanaa Kaanum Kaalangal', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kanaa%20Kaanum%20Kaalangal%20AR%20Rahman' },
    ],
    hindi: [
      { name: 'Lag Ja Gale', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lag%20Ja%20Gale%20Lata' },
      { name: 'Yeh Dosti', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Yeh%20Dosti%20Kishore' },
      { name: 'Zindagi Ek Safar', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Zindagi%20Ek%20Safar' },
      { name: 'Ajeeb Dastan Hai Yeh', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ajeeb%20Dastan%20Hai%20Yeh' },
      { name: 'Ek Pyaar Ka Nagma Hai', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ek%20Pyaar%20Ka%20Nagma' },
      { name: 'Yeh Zindagi Usi Ki Hai', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Yeh%20Zindagi%20Usi%20Ki%20Hai' },
      { name: 'Ae Mere Watan Ke Logo', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ae%20Mere%20Watan%20Ke%20Logo%20Lata' },
      { name: 'Roop Tera Mastana', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Roop%20Tera%20Mastana%20Kishore' },
      { name: 'Mere Sapno Ki Rani', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mere%20Sapno%20Ki%20Rani%20Kishore' },
      { name: 'Tere Bina Zindagi', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tere%20Bina%20Zindagi%20Kishore' },
      { name: 'Chalte Chalte', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chalte%20Chalte%20Kishore%20Kumar' },
      { name: 'Yeh Shaam Mastani', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Yeh%20Shaam%20Mastani%20Kishore' },
      { name: 'Main Shayar Toh Nahin', artist: 'Shailendra Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Main%20Shayar%20Toh%20Nahin' },
      { name: 'Yaar Dost', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Yaar%20Dost%20Hindi%20classic' },
      { name: 'Tum Hi Mere Mandir', artist: 'Lata Mangeshkar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tum%20Hi%20Mere%20Mandir%20Lata' },
      { name: 'Wada Karo Nahin Chodoge', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wada%20Karo%20Nahin%20Chodoge' },
      { name: 'Pal Pal Dil Ke Paas', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pal%20Pal%20Dil%20Ke%20Paas%20Kishore' },
      { name: 'Ye Dil Tum Bin', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ye%20Dil%20Tum%20Bin%20Kishore' },
      { name: 'Zindagi Kaisi Hai Paheli', artist: 'Manna Dey', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Zindagi%20Kaisi%20Hai%20Paheli%20Manna%20Dey' },
      { name: 'Neele Neele Ambar Par', artist: 'Kishore Kumar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Neele%20Neele%20Ambar%20Par%20Kishore' },
    ],
    english: [
      { name: 'Imagine', artist: 'John Lennon', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Imagine%20John%20Lennon' },
      { name: 'Hotel California', artist: 'Eagles', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hotel%20California%20Eagles' },
      { name: 'Bohemian Rhapsody', artist: 'Queen', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bohemian%20Rhapsody%20Queen' },
      { name: 'Let It Be', artist: 'The Beatles', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Let%20It%20Be%20Beatles' },
      { name: 'Wonderwall', artist: 'Oasis', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wonderwall%20Oasis' },
      { name: 'Stairway to Heaven', artist: 'Led Zeppelin', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Stairway%20To%20Heaven%20Led%20Zeppelin' },
      { name: 'Yesterday', artist: 'The Beatles', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Yesterday%20The%20Beatles' },
      { name: 'Hey Jude', artist: 'The Beatles', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hey%20Jude%20Beatles' },
      { name: 'Sound of Silence', artist: 'Simon and Garfunkel', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sound%20Of%20Silence%20Simon%20Garfunkel' },
      { name: 'Bridge Over Troubled Water', artist: 'Simon and Garfunkel', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bridge%20Over%20Troubled%20Water' },
      { name: 'Comfortably Numb', artist: 'Pink Floyd', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Comfortably%20Numb%20Pink%20Floyd' },
      { name: 'Wish You Were Here', artist: 'Pink Floyd', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Wish%20You%20Were%20Here%20Pink%20Floyd' },
      { name: 'Behind Blue Eyes', artist: 'The Who', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Behind%20Blue%20Eyes%20The%20Who' },
      { name: 'Piano Man', artist: 'Billy Joel', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Piano%20Man%20Billy%20Joel' },
      { name: 'Mr Brightside', artist: 'The Killers', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mr%20Brightside%20The%20Killers' },
      { name: 'Losing My Religion', artist: 'REM', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Losing%20My%20Religion%20REM' },
      { name: 'Creep', artist: 'Radiohead', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Creep%20Radiohead' },
      { name: 'Mad World', artist: 'Gary Jules', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mad%20World%20Gary%20Jules' },
      { name: 'Landslide', artist: 'Fleetwood Mac', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Landslide%20Fleetwood%20Mac' },
      { name: 'Fast Car', artist: 'Tracy Chapman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Fast%20Car%20Tracy%20Chapman' },
    ],
    telugu: [
      { name: 'Annamayya Keerthana', artist: 'SP Balasubrahmanyam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Annamayya%20SPB' },
      { name: 'Evaro Evaro', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Evaro%20Evaro%20Telugu' },
      { name: 'Nee Cheli', artist: 'SP Balasubrahmanyam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nee%20Cheli%20SPB' },
      { name: 'Manmadhudu Theme', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Manmadhudu%20Telugu' },
      { name: 'Ye Tara', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ye%20Tara%20Telugu' },
      { name: 'Nuvvu Nenu Prema', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nuvvu%20Nenu%20Prema%20Telugu' },
      { name: 'Jallu Jallu Jallundi', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jallu%20Jallu%20Jallundi%20Telugu' },
      { name: 'Nannaku Prematho', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nannaku%20Prematho%20DSP' },
      { name: 'Gunde Jaari Gallanthayyinde', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gunde%20Jaari%20Gallanthayyinde%20Telugu' },
      { name: 'Ee Varsham Paatuga', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ee%20Varsham%20Paatuga%20Telugu' },
      { name: 'Naa Peru Surya', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Naa%20Peru%20Surya%20DSP' },
      { name: 'Bangaru Kodi Petta', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bangaru%20Kodi%20Petta%20Telugu' },
      { name: 'Avunu Valliddaru', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Avunu%20Valliddaru%20Telugu' },
      { name: 'Ninnu Kori', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ninnu%20Kori%20Telugu' },
      { name: 'Hello Guru Prema Kosame', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hello%20Guru%20Prema%20Kosame%20DSP' },
      { name: 'Oopiri Theme', artist: 'Anup Rubens', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oopiri%20Theme%20Telugu' },
      { name: 'Ekkadiki Pothavu Chinnavada', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ekkadiki%20Pothavu%20Chinnavada%20Telugu' },
      { name: 'Janatha Garage', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Janatha%20Garage%20DSP' },
      { name: 'Mahanati Theme', artist: 'Mickey J Meyer', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mahanati%20Theme%20Telugu' },
      { name: 'Pellichoopulu Title Song', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pellichoopulu%20Title%20Song%20Telugu' },
    ],
  },
  fearful: {
    tamil: [
      { name: 'Suprabhatham', artist: 'MS Subbulakshmi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Suprabhatham%20MS%20Subbulakshmi' },
      { name: 'Thiruppugazh', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thiruppugazh%20Tamil' },
      { name: 'Karpagame', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Karpagame%20Ilaiyaraaja' },
      { name: 'Murugan Devotional', artist: 'SPB', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Murugan%20Songs%20SPB' },
      { name: 'Om Namah Shivaya', artist: 'SPB', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Om%20Namah%20Shivaya%20Tamil' },
      { name: 'Vinayagar Agaval', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vinayagar%20Agaval%20Tamil' },
      { name: 'Kandha Sashti Kavasam', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kandha%20Sashti%20Kavasam' },
      { name: 'Abirami Andhadhi', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Abirami%20Andhadhi%20Tamil' },
      { name: 'Thiruvasagam', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Thiruvasagam%20AR%20Rahman' },
      { name: 'Arul Tharuvar', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Arul%20Tharuvar%20Tamil' },
      { name: 'Sharanam Sharanam', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sharanam%20Sharanam%20Tamil' },
      { name: 'Sri Rama Jayam', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sri%20Rama%20Jayam%20Tamil' },
      { name: 'Siva Siva', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Siva%20Siva%20Tamil%20devotional' },
      { name: 'Vel Vel Muruga', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vel%20Vel%20Muruga%20Tamil' },
      { name: 'Amman Devotional', artist: 'SPB', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Amman%20Devotional%20SPB%20Tamil' },
    ],
    hindi: [
      { name: 'Hanuman Chalisa', artist: 'Hariharan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hanuman%20Chalisa%20Hariharan' },
      { name: 'Om Jai Jagdish', artist: 'Anuradha Paudwal', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Om%20Jai%20Jagdish%20Hare' },
      { name: 'Gayatri Mantra', artist: 'Anuradha Paudwal', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gayatri%20Mantra' },
      { name: 'Mahamrityunjaya Mantra', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mahamrityunjaya%20Mantra' },
      { name: 'Jai Ambe Gauri', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jai%20Ambe%20Gauri' },
      { name: 'Shree Ram Chandra', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shree%20Ram%20Chandra%20Devotional' },
      { name: 'Jai Shree Ram', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jai%20Shree%20Ram%20Bhajan' },
      { name: 'Achyutam Keshavam', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Achyutam%20Keshavam' },
      { name: 'Jai Ganesh Deva', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jai%20Ganesh%20Deva%20Hindi' },
      { name: 'Shiv Tandav Stotram', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shiv%20Tandav%20Stotram' },
      { name: 'Om Namah Shivaya Hindi', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Om%20Namah%20Shivaya%20Hindi' },
      { name: 'Durga Chalisa', artist: 'Anuradha Paudwal', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Durga%20Chalisa%20Anuradha%20Paudwal' },
      { name: 'Vishnu Sahasranamam', artist: 'MS Subbulakshmi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vishnu%20Sahasranamam' },
      { name: 'Sai Baba Bhajan', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sai%20Baba%20Bhajan%20Hindi' },
      { name: 'Krishna Bhajan', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Krishna%20Bhajan%20Hindi' },
    ],
    english: [
      { name: 'Moonlight Sonata', artist: 'Beethoven', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Moonlight%20Sonata%20Beethoven' },
      { name: 'Clair de Lune', artist: 'Debussy', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Clair%20De%20Lune%20Debussy' },
      { name: 'Canon in D', artist: 'Pachelbel', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Canon%20In%20D%20Pachelbel' },
      { name: 'Ave Maria', artist: 'Schubert', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ave%20Maria%20Schubert' },
      { name: 'Fur Elise', artist: 'Beethoven', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Fur%20Elise%20Beethoven' },
      { name: 'Symphony No 5', artist: 'Beethoven', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Symphony%20No%205%20Beethoven' },
      { name: 'Eine Kleine Nachtmusik', artist: 'Mozart', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Eine%20Kleine%20Nachtmusik%20Mozart' },
      { name: 'Air on G String', artist: 'Bach', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Air%20On%20G%20String%20Bach' },
      { name: 'Four Seasons Spring', artist: 'Vivaldi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Four%20Seasons%20Spring%20Vivaldi' },
      { name: 'Nocturne Op 9', artist: 'Chopin', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nocturne%20Op%209%20Chopin' },
      { name: 'Hallelujah', artist: 'Leonard Cohen', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hallelujah%20Leonard%20Cohen' },
      { name: 'Benedictus', artist: 'Karl Jenkins', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Benedictus%20Karl%20Jenkins' },
      { name: 'Nessun Dorma', artist: 'Puccini', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nessun%20Dorma%20Puccini' },
      { name: 'Pie Jesu', artist: 'Andrew Lloyd Webber', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pie%20Jesu%20Andrew%20Lloyd%20Webber' },
      { name: 'Amazing Grace', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Amazing%20Grace%20Classical' },
    ],
    telugu: [
      { name: 'Venkateswara Suprabhatham', artist: 'MS Subbulakshmi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Venkateswara%20Suprabhatham' },
      { name: 'Annamayya Devotional', artist: 'SP Balasubrahmanyam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Annamayya%20Devotional%20SPB' },
      { name: 'Govinda Namalu', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Govinda%20Namalu%20Telugu' },
      { name: 'Durga Devi Stotram', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Durga%20Stotram%20Telugu' },
      { name: 'Lalitha Sahasranamam', artist: 'MS Subbulakshmi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lalitha%20Sahasranamam' },
      { name: 'Bhavayami Gopala Balam', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bhavayami%20Gopala%20Balam%20Telugu' },
      { name: 'Sri Rama Navami', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sri%20Rama%20Navami%20Telugu' },
      { name: 'Devi Stotram Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Devi%20Stotram%20Telugu' },
      { name: 'Ashtakam Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ashtakam%20Telugu%20devotional' },
      { name: 'Balaji Devotional', artist: 'SP Balasubrahmanyam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Balaji%20Devotional%20SPB%20Telugu' },
    ],
  },
  disgusted: {
    tamil: [
      { name: 'Carnatic Flute', artist: 'N Ramani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Carnatic%20Flute%20N%20Ramani' },
      { name: 'Veena Meditation', artist: 'E Gayathri', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Veena%20Classical%20Tamil' },
      { name: 'Tamil Instrumental', artist: 'Ilaiyaraaja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tamil%20Instrumental%20Ilaiyaraaja' },
      { name: 'Nadhaswaram Classical', artist: 'Traditional', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nadhaswaram%20Classical' },
      { name: 'Sitar Tamil Ragas', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sitar%20Tamil%20Ragas' },
      { name: 'Raga Bhairavi Tamil', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Raga%20Bhairavi%20Tamil%20Classical' },
      { name: 'Flute Raga Tamil', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Flute%20Raga%20Tamil%20Classical' },
      { name: 'Mridangam Classical', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mridangam%20Classical%20Tamil' },
      { name: 'Violin Carnatic', artist: 'L Subramaniam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Violin%20Carnatic%20L%20Subramaniam' },
      { name: 'Tambura Meditation', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Tambura%20Meditation%20Tamil' },
    ],
    hindi: [
      { name: 'Raag Yaman', artist: 'Pandit Ravi Shankar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Raag%20Yaman%20Ravi%20Shankar' },
      { name: 'Flute Meditation', artist: 'Hariprasad Chaurasia', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Hariprasad%20Chaurasia%20Flute' },
      { name: 'Tabla Classical', artist: 'Zakir Hussain', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Zakir%20Hussain%20Tabla' },
      { name: 'Sitar Bhairavi', artist: 'Vilayat Khan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vilayat%20Khan%20Sitar' },
      { name: 'Morning Ragas', artist: 'Pandit Ravi Shankar', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Morning%20Ragas%20Ravi%20Shankar' },
      { name: 'Raag Darbari', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Raag%20Darbari%20Classical' },
      { name: 'Sarod Classical', artist: 'Amjad Ali Khan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sarod%20Classical%20Amjad%20Ali%20Khan' },
      { name: 'Bansuri Meditation', artist: 'Pandit Hariprasad', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bansuri%20Meditation%20Hariprasad' },
      { name: 'Shehnai Classical', artist: 'Bismillah Khan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shehnai%20Classical%20Bismillah%20Khan' },
      { name: 'Santoor Meditation', artist: 'Shivkumar Sharma', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Santoor%20Meditation%20Shivkumar%20Sharma' },
    ],
    english: [
      { name: 'Lofi Hip Hop Beats', artist: 'ChilledCow', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lofi%20Hip%20Hop%20Beats' },
      { name: 'Rain Sounds', artist: 'Nature Sounds', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rain%20Sounds%20Relaxing' },
      { name: 'Ocean Waves', artist: 'Nature Sounds', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ocean%20Waves%20Relaxing' },
      { name: 'Piano Meditation', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Piano%20Meditation%20Music' },
      { name: 'Study Lofi', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Study%20Lofi%20Music' },
      { name: 'Forest Sounds', artist: 'Nature Sounds', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Forest%20Sounds%20Relaxing' },
      { name: 'Ambient Music', artist: 'Brian Eno', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ambient%20Music%20Brian%20Eno' },
      { name: 'Weightless', artist: 'Marconi Union', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Weightless%20Marconi%20Union' },
      { name: 'Sleep Music', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sleep%20Music%20Relaxing' },
      { name: 'Healing Frequency', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Healing%20Frequency%20Music' },
    ],
    telugu: [
      { name: 'Telugu Flute Classical', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Telugu%20Flute%20Classical' },
      { name: 'Carnatic Violin', artist: 'L Subramaniam', artwork: '', spotifyUrl: 'https://open.spotify.com/search/L%20Subramaniam%20Violin' },
      { name: 'Veena Classical Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Veena%20Classical%20Telugu' },
      { name: 'Telugu Meditation', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Telugu%20Meditation%20Music' },
      { name: 'Sitar Ragas Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sitar%20Ragas%20Telugu' },
      { name: 'Flute Ragas Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Flute%20Ragas%20Telugu%20Classical' },
      { name: 'Classical Music Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Classical%20Music%20Telugu' },
      { name: 'Instrumental Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Instrumental%20Telugu%20Meditation' },
      { name: 'Mandolin Classical', artist: 'U Shrinivas', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Mandolin%20Classical%20U%20Shrinivas' },
      { name: 'Nadaswaram Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Nadaswaram%20Telugu%20Classical' },
    ],
  },
  surprised: {
    tamil: [
      { name: 'Why This Kolaveri Di', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Why%20This%20Kolaveri%20Di' },
      { name: 'Selfie Pulla', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Selfie%20Pulla%20Anirudh' },
      { name: 'Maari Thara Local', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Maari%20Thara%20Local' },
      { name: 'Iphone Kaadhali', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Iphone%20Kaadhali%20Anirudh' },
      { name: 'Taxi Taxi', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Taxi%20Taxi%20Tamil' },
      { name: 'Chellamma', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chellamma%20Anirudh' },
      { name: 'Sodakku', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Sodakku%20Anirudh' },
      { name: 'Aalaporan Tamizhan', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Aalaporan%20Tamizhan%20AR%20Rahman' },
      { name: 'Vera Level', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Vera%20Level%20Anirudh' },
      { name: 'Chella Kutti', artist: 'AR Rahman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Chella%20Kutti%20AR%20Rahman' },
      { name: 'Naan Ready', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Naan%20Ready%20Anirudh' },
      { name: 'Oru Kai Adutha', artist: 'Yuvan Shankar Raja', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oru%20Kai%20Adutha%20Yuvan' },
      { name: 'Kannaana Kanney Fun', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kannaana%20Kanney%20fun%20Anirudh' },
      { name: 'Dippam Dippam', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dippam%20Dippam%20Anirudh' },
      { name: 'Oh Maama', artist: 'Anirudh Ravichander', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oh%20Maama%20Anirudh' },
    ],
    hindi: [
      { name: 'Lungi Dance', artist: 'Yo Yo Honey Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Lungi%20Dance%20Honey%20Singh' },
      { name: 'Party Toh Banti Hai', artist: 'Mika Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Party%20Toh%20Banti%20Hai' },
      { name: 'Abhi Toh Party Shuru Hui Hai', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Abhi%20Toh%20Party%20Shuru%20Hui' },
      { name: 'Saturday Saturday', artist: 'Indeep Bakshi', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Saturday%20Saturday%20Indeep%20Bakshi' },
      { name: 'Desi Beat', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Desi%20Beat%20Badshah' },
      { name: 'Jai Jai Shiv Shankar Fun', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Jai%20Jai%20Shiv%20Shankar%20fun' },
      { name: 'Saware', artist: 'Arijit Singh', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Saware%20Arijit%20Singh' },
      { name: 'Baat Ban Jaye', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Baat%20Ban%20Jaye%20Hindi' },
      { name: 'Banjaara', artist: 'Mohammed Irfan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Banjaara%20Mohammed%20Irfan' },
      { name: 'Fun Karo', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Fun%20Karo%20Hindi%20peppy' },
      { name: 'Zindagi Aa Raha Hoon', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Zindagi%20Aa%20Raha%20Hoon%20Hindi' },
      { name: 'Ghabrana Nahi Hai', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ghabrana%20Nahi%20Hai%20Hindi' },
      { name: 'Aaj Ki Raat', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Aaj%20Ki%20Raat%20Hindi%20party' },
      { name: 'Kala Chashma', artist: 'Badshah', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kala%20Chashma%20Badshah' },
      { name: 'Ole Ole', artist: 'Udit Narayan', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ole%20Ole%20Udit%20Narayan' },
    ],
    english: [
      { name: 'Shake It Off', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Shake%20It%20Off%20Taylor%20Swift' },
      { name: 'Roar', artist: 'Katy Perry', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Roar%20Katy%20Perry' },
      { name: 'Dynamite', artist: 'BTS', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dynamite%20BTS' },
      { name: 'Blinding Lights', artist: 'The Weeknd', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Blinding%20Lights%20Weeknd' },
      { name: 'Levitating', artist: 'Dua Lipa', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Levitating%20Dua%20Lipa' },
      { name: 'Supalonely', artist: 'Benee', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Supalonely%20Benee' },
      { name: 'Watermelon Sugar', artist: 'Harry Styles', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Watermelon%20Sugar%20Harry%20Styles' },
      { name: 'Intentions', artist: 'Justin Bieber', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Intentions%20Justin%20Bieber' },
      { name: 'Rain On Me', artist: 'Lady Gaga', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rain%20On%20Me%20Lady%20Gaga' },
      { name: 'As It Was', artist: 'Harry Styles', artwork: '', spotifyUrl: 'https://open.spotify.com/search/As%20It%20Was%20Harry%20Styles' },
      { name: 'Anti-Hero', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Anti-Hero%20Taylor%20Swift' },
      { name: 'Flowers', artist: 'Miley Cyrus', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Flowers%20Miley%20Cyrus' },
      { name: 'Cruel Summer', artist: 'Taylor Swift', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Cruel%20Summer%20Taylor%20Swift' },
      { name: 'Butter', artist: 'BTS', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Butter%20BTS' },
      { name: 'Boy With Luv', artist: 'BTS', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Boy%20With%20Luv%20BTS' },
    ],
    telugu: [
      { name: 'Dhinka Chika', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Dhinka%20Chika%20Telugu' },
      { name: 'Rangamma Mangamma', artist: 'SS Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rangamma%20Mangamma%20Telugu' },
      { name: 'Pattas Theme', artist: 'Vivek Mervin', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Pattas%20Telugu' },
      { name: 'Uppena Fun Song', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Uppena%20Songs%20Telugu' },
      { name: 'Rowdy Baby Telugu', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Rowdy%20Baby%20Telugu' },
      { name: 'Naatu Naatu', artist: 'MM Keeravani', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Naatu%20Naatu' },
      { name: 'Butta Bomma', artist: 'Armaan Malik', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Butta%20Bomma' },
      { name: 'Kurchi Madathapetti', artist: 'Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kurchi%20Madathapetti%20Telugu' },
      { name: 'Kushi Fun', artist: 'Hesham Abdul Wahab', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Kushi%20Telugu%20fun%20song' },
      { name: 'Waltair Veerayya Fun', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Waltair%20Veerayya%20fun%20DSP' },
      { name: 'Oo Antava Fun', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Oo%20Antava%20fun%20DSP' },
      { name: 'Seeti Maar Fun', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Seeti%20Maar%20fun%20Telugu' },
      { name: 'Ramuloo Ramulaa', artist: 'Thaman', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Ramuloo%20Ramulaa%20Telugu' },
      { name: 'Bholaa Shankar Fun', artist: 'DSP', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Bholaa%20Shankar%20fun%20DSP' },
      { name: 'Gam Gam Ganesha', artist: 'Various', artwork: '', spotifyUrl: 'https://open.spotify.com/search/Gam%20Gam%20Ganesha%20Telugu' },
    ],
  },
};

const getRecommendations = async (req, res) => {
  try {
    const { emotion, language, userEmail } = req.query;

    if (!emotion || !language) {
      return res.status(400).json({ message: 'emotion and language required' });
    }

    const emotionLower = emotion.toLowerCase();
    const languageLower = language.toLowerCase();

    // ✅ MongoDB Mood History save
    if (userEmail) {
      try {
        await MoodHistory.create({
          userEmail,
          emotion: emotionLower,
          language: languageLower,
        });
        console.log(`✅ Mood saved: ${userEmail} → ${emotionLower} → ${languageLower}`);
      } catch (dbErr) {
        console.log('⚠️ Mood save skipped:', dbErr.message);
      }
    }

    // ✅ Database-லிருந்து songs எடு
    const songs = songDatabase[emotionLower]?.[languageLower] || [];

    if (songs.length === 0) {
      console.log(`⚠️ No songs for ${emotionLower}+${languageLower}`);
      return res.json({ songs: [], emotion: emotionLower, language: languageLower });
    }

    console.log(`✅ Returning ${songs.length} songs for ${emotionLower}+${languageLower}`);
    res.json({ songs, emotion: emotionLower, language: languageLower });

  } catch (error) {
    console.error('❌ Error:', error.message);
    res.status(500).json({ message: 'Error', error: error.message });
  }
};

module.exports = { getRecommendations };